# -*- coding: utf-8 -*-
"""week 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1caLya0lq9i9fZAkrWyVj3BgSODC0rmeo
"""

import numpy as np
import pandas as pd
import math

# Week 1 Dataset
df = pd.read_csv('https://raw.githubusercontent.com/MichiganDataScienceTeam/f25-building-ml-models/refs/heads/main/week-1/dataset.csv')

# TODO: First view the input data using head(), then store the top 5 inputs in a np array
# Hint: List[:x] can extract the first x elements of a python list
inputs = np.array(df['Value'].iloc[:5])
def sigmoid(x: int) -> float:
  """Sigmoid activation function."""
  return 1 / (1 + math.exp(-x))
class Perceptron:
  """Neuron class object representing perceptron."""

  def __init__(self, num_inputs: int, weights = None) -> None:
    """Init weights and other information."""

    self.num_inputs = num_inputs

    if weights is None:
      self.weights = np.random.uniform(-1, 1, num_inputs)
    else:
      self.weights = weights

  def feed_forward(self, inputs: np.array) -> float:
    """Forward propogation step."""

    output = None
    weighted_sum = np.dot(inputs, self.weights)
    output = sigmoid(weighted_sum)

    # TODO: complete feed forward algorithm below
    return output

def main():
  """Test Perceptron class here."""

  # TODO: Declare your perceptron class below, run your feed_forward algorithm
  # BONUS: declare an array of weights to pass into your perceptron so the output of the forward pass is 0.5

  out = 0
  print(inputs)
  p = Perceptron(inputs.shape[0])
  out = p.feed_forward(inputs)

  print(f"Perceptron output after forward propagation: {out:.2f}")

  q = Perceptron(inputs.shape[0], [0, 0, 0, 0, 0])
  out = q.feed_forward(inputs)

  print(f"Perceptron output after forward propagation and custom weights: {out:.2f}")

main()